//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dragon_Library.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentPrototypeLimit
    {
        public int EquipmentPrototypeLimit_ID { get; set; }
        public Nullable<int> EquipmentPrototype_ID { get; set; }
        public Nullable<int> Limit_Lv { get; set; }
        public Nullable<int> Limit_Con { get; set; }
        public Nullable<int> Limit_Str { get; set; }
        public Nullable<int> Limit_Vit { get; set; }
        public Nullable<int> Limit_Spd { get; set; }
        public Nullable<int> Limit_Int { get; set; }
    
        public virtual EquipmentPrototype EquipmentPrototype { get; set; }
    }
}
