//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dragon_Library.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberRole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MemberRole()
        {
            this.MemberRoleStatus = new HashSet<MemberRoleStatus>();
            this.RoleAttrsDetail = new HashSet<RoleAttrsDetail>();
        }
    
        public int MemberRole_ID { get; set; }
        public string MemberRole_Name { get; set; }
        public bool MemberRole_Gender { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int MemberRole_Golds { get; set; }
        public int MemberRole_Exp { get; set; }
        public int MemberRole_ArenaPoints { get; set; }
        public int ArenaTitle_ID { get; set; }
        public int Member_ID { get; set; }
        public int MemberRoleImg_ID { get; set; }
        public int Con { get; set; }
        public int Str { get; set; }
        public int Vit { get; set; }
        public int Spd { get; set; }
        public int Int { get; set; }
    
        public virtual ArenaTitle ArenaTitle { get; set; }
        public virtual Member Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberRoleStatus> MemberRoleStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleAttrsDetail> RoleAttrsDetail { get; set; }
        public virtual MemberRoleImg MemberRoleImg { get; set; }
    }
}
