//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dragon_Library.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberRoleStatus
    {
        public int MemberRoleStatus_ID { get; set; }
        public int MemberRole_ID { get; set; }
        public Nullable<double> HP { get; set; }
        public Nullable<double> MP { get; set; }
        public Nullable<double> Atk { get; set; }
        public Nullable<double> Def { get; set; }
        public Nullable<double> Agi { get; set; }
        public Nullable<double> Spi { get; set; }
        public Nullable<double> Res { get; set; }
    
        public virtual MemberRole MemberRole { get; set; }
    }
}
