//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dragon_Library.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Options
    {
        public long Option_ID { get; set; }
        public int Subject_ID { get; set; }
        public string Option_Name { get; set; }
        public string FileName { get; set; }
        public bool IsAnswer { get; set; }
    
        public virtual Subject Subject { get; set; }
    }
}
