//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dragon_Library.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.Course1 = new HashSet<Course>();
            this.CourseGrammarDetail = new HashSet<CourseGrammarDetail>();
            this.CourseSentenceDetail = new HashSet<CourseSentenceDetail>();
            this.CourseWordDetail = new HashSet<CourseWordDetail>();
            this.StoryCourseDetail = new HashSet<StoryCourseDetail>();
            this.Member = new HashSet<Member>();
        }
    
        public int Course_ID { get; set; }
        public Nullable<int> Parent_ID { get; set; }
        public int BookEdition_ID { get; set; }
        public byte Course_Level { get; set; }
        public string Course_Name { get; set; }
        public string Course_No { get; set; }
        public string Course_Image { get; set; }
        public Nullable<byte> Sort { get; set; }
    
        public virtual BookEdition BookEdition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course> Course1 { get; set; }
        public virtual Course Course2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseGrammarDetail> CourseGrammarDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseSentenceDetail> CourseSentenceDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseWordDetail> CourseWordDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoryCourseDetail> StoryCourseDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Member> Member { get; set; }
    }
}
