//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dragon_Library.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class StroyMapping
    {
        public int StoryMapping_ID { get; set; }
        public Nullable<int> StoryTelling_ID { get; set; }
        public Nullable<int> StoryTellingImg_ID { get; set; }
        public int Sort { get; set; }
        public int Seconds { get; set; }
        public int StoryStoreInfo_ID { get; set; }
    
        public virtual StoryStoreInfo StoryStoreInfo { get; set; }
        public virtual StoryTelling StoryTelling { get; set; }
        public virtual StoryTellingImg StoryTellingImg { get; set; }
    }
}
